GET http://localhost:3333/

###
POST http://localhost:3333/add
Content-Type: application/json

{
    "name" : "reguar plantas!!"
}

###

PUT http://localhost:3333/update/e55d01e7-9c54-490d-9620-59fea53632bb
Content-Type: application/json

{
    "name" : "remover lixo"
}

###

DELETE http://localhost:3333/delete/fff28c4f-15e3-4289-af0c-ee7face387d3